version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    desc: List tasks (default)
    cmds:
      - cmd: task -l
        silent: true

  tdd_demo:run:
    desc: Runs main
    dir: tdd_demo
    cmds:
      - uv run src/main.py

  tdd_demo:test:
    desc: Tests the Calculator
    dir: tdd_demo
    cmds:
      - uv run pytest
